alert("hello world");
alert("Hello, World!");
console.log("Hello, World!");
prompt("Hello, World!");
console.log("this is a test");
console.log("this is a test msg");
console.log("this is another console msg");
let message = "Hello, World!";
console.log(message);
let name = prompt("What is your name?");
console.log("Hello, " + name + "!");
document.write("Hello, " + name + "!");

console.log("hello world");
let greeting = "Hello, World!";
console.log(greeting);
console.log("This is a test message.");
console.log("this is another console message.");
let a =[1,2,3,4,5];
console.log(a);
a.push(10);
a.pop();
console.log(a);